---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: dfbc26e307c9724b75782d6799087ed2269b0cd9
      fabric8.io/git-branch: main
      fabric8.io/git-url: https://github.com/abraham1255/concluir-expediente-mock.git
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/concluir-expediente-ws-mock
      fabric8.io/scm-tag: HEAD
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      app: concluir-expediente-ws-mock
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: com.example
    name: concluir-expediente-ws-mock
  spec:
    ports:
    - name: us-cli
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: concluir-expediente-ws-mock
      provider: fabric8
      group: com.example
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: dfbc26e307c9724b75782d6799087ed2269b0cd9
      fabric8.io/git-branch: main
      fabric8.io/git-url: https://github.com/abraham1255/concluir-expediente-mock.git
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/concluir-expediente-ws-mock
      fabric8.io/scm-tag: HEAD
    labels:
      app: concluir-expediente-ws-mock
      provider: fabric8
      version: 0.0.1-SNAPSHOT
      group: com.example
    name: concluir-expediente-ws-mock
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: concluir-expediente-ws-mock
        provider: fabric8
        group: com.example
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: dfbc26e307c9724b75782d6799087ed2269b0cd9
          fabric8.io/git-branch: main
          fabric8.io/scm-tag: HEAD
          fabric8.io/git-url: https://github.com/abraham1255/concluir-expediente-mock.git
          fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/concluir-expediente-ws-mock
        labels:
          app: concluir-expediente-ws-mock
          provider: fabric8
          version: 0.0.1-SNAPSHOT
          group: com.example
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: concluir-expediente-ws-mock:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8082
            name: us-cli
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
